Attribute VB_Name = "ClassRecordDimM"
Attribute VB_Base = "0{FCFB3D2A-A0FA-1068-A738-08002B3371B5}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False
Option Explicit
'Public SelMgr As Object
Public SelMgr As SldWorks.SelectionMgr
Public m As Integer ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
Public m1 As Integer ' |fffd||fffd||fffd||fffd||fffd|  |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Public m2 As Integer ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
Public FormLeft As Integer
Public FormTop As Integer
Public WithEvents swApp As SldWorks.SldWorks
Attribute swApp.VB_VarHelpID = -1
'Public ModelDoc2 As Object
Public ModelDoc2 As SldWorks.ModelDoc2
Public WithEvents MyDrw As SldWorks.DrawingDoc
Attribute MyDrw.VB_VarHelpID = -1
Public WithEvents MyPart As SldWorks.PartDoc
Attribute MyPart.VB_VarHelpID = -1
Public WithEvents MyAssem As SldWorks.AssemblyDoc
Attribute MyAssem.VB_VarHelpID = -1

Public Sub MonitorSolidWorks()
'Debug.Print "MonitorSolidWorks"
Set swApp = Application.SldWorks
Test
End Sub

Private Sub ShowFrm() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
If m1 = 1 Then
    FrmRecordDimM.Left = FormLeft
    FrmRecordDimM.Top = FormTop
End If
If m = 1 Then
    FrmRecordDimM.UserForm_Activate
Else
    FrmRecordDimM.Show vbModeless
End If
m = 1
End Sub

Private Function MyDrw_DimensionChangeNotify(ByVal displayDim As Object) As Long
    'Debug.Print "MyDrw_DimensionChangeNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function MyDrw_NewSelectionNotify() As Long
    'Debug.Print "MyDrw_NewSelectionNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function MyPart_DimensionChangeNotify(ByVal displayDim As Object) As Long
    'Debug.Print "MyPart_DimensionChangeNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function MyPart_NewSelectionNotify() As Long
    'Debug.Print "MyPart_NewSelectionNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function MyAssem_DimensionChangeNotify(ByVal displayDim As Object) As Long
    'Debug.Print "MyAssem_DimensionChangeNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function MyAssem_NewSelectionNotify() As Long
    'Debug.Print "MyAssem_NewSelectionNotify"
    FormLeft = FrmRecordDimM.Left
    FormTop = FrmRecordDimM.Top
    m1 = 1
    main
End Function

Private Function swApp_ActiveModelDocChangeNotify() As Long
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    Test
End Function

Private Sub Test() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
Set ModelDoc2 = swApp.ActiveDoc
m2 = 0
If swApp.ActiveDoc Is Nothing Then
    m2 = 1
    FrmRecordDimM.LblFirst.Caption = "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    FrmRecordDimM.LblSecond.Caption = ""
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
ElseIf swApp.ActiveDoc.GetType = swDocDRAWING Then
    Set MyDrw = swApp.ActiveDoc
    'Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
ElseIf swApp.ActiveDoc.GetType = swDocPART Then
    Set MyPart = swApp.ActiveDoc
    'Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
ElseIf swApp.ActiveDoc.GetType = swDocASSEMBLY Then
    Set MyAssem = swApp.ActiveDoc
    'Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
Else
    m2 = 1
    FrmRecordDimM.LblFirst.Caption = "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    FrmRecordDimM.LblSecond.Caption = ""
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
End If
If m2 = 0 Then
    Set SelMgr = ModelDoc2.SelectionManager
    If SelMgr.GetSelectedObjectCount = 1 Then ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        If SelMgr.GetSelectedObjectType(1) <> swSelDIMENSIONS Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
            FrmRecordDimM.LblFirst.Caption = "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
            FrmRecordDimM.LblSecond.Caption = ""
            m2 = 1
        End If
    Else
        FrmRecordDimM.LblFirst.Caption = "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
        FrmRecordDimM.LblSecond.Caption = ""
        m2 = 1
    End If
End If
ShowFrm
End Sub

Attribute VB_Name = "FrmRecordDimM"
Attribute VB_Base = "0{D68C5C21-4D3F-47EA-89D1-8A22D783A208}{0FA8A8AF-92E9-49A2-9715-5F2D9F6F1E94}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False
Option Explicit
'Dim DimProp As Object
Dim DimProp As SldWorks.DisplayDimension
Dim DispData As SldWorks.DisplayData
Dim DPValue As Double
Dim DPValuePr As Double
'Dim DP As Object
Dim DP As SldWorks.Dimension
Dim i As Byte
Dim StartStr As String
Dim StartStr2 As String
Dim EndStr As String
Dim BottomStr As String
Dim StartStrPr As String
Dim StartStr2Pr As String
Dim ENDstrPr As String
Dim BottomStrPr As String
Dim Suffix As String
Dim Prefix As String
Dim CalloutBelow As String
Dim DisplayDataText As String
Dim Col As Integer
Dim StepValue As Double
Dim varTemp As Variant
Dim varTemp1 As Variant
Dim varTemp2 As Variant
Dim varTemp3 As Variant
Dim strTemp As String
Dim AStr As String
Dim Numb As String
Dim sLeft As String
Dim sStep As String
Dim sDop As String
Dim DimPrec As Long
Dim BrokenLeaderRet As Long
Dim Offset As Variant
Dim m3 As Integer ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| m3 = 0 - |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|, m3 = 1 - |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Dim m4 As Integer ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
Dim m5 As Integer ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Dim sDeg As String
Dim m_OptDim As Integer
Dim m_ColEl  As Integer
Dim m_fask As Integer
Dim m_Otv As Integer
Dim m_RezOvt As Integer
Dim m_Rad As Integer
Dim m_OptPaz As Integer
Dim m_OptExt As Integer
Dim m_OptPlace As Integer
Dim m_Massiv As Integer
Dim cop As Boolean
Dim ok As Boolean
Dim bNewDim As Boolean
Dim sNewDim As String
Dim bNewStep As Boolean

Private Sub TogButFormat_Click()
'If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Else ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If TogButFormat.Value = True Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
        Debug.Print "TogButFormat.Value = True"
        m5 = 1
        CommandButton1_Click
        CommandButton1.Enabled = False
        CmdClose.Enabled = False
        CmdCancel.Enabled = False
    Else ' |fffd||fffd||fffd||fffd||fffd||fffd|
        Debug.Print "TogButFormat.Value = False"
        m5 = 0
        CommandButton1.Enabled = True
        CmdClose.Enabled = True
        CmdCancel.Enabled = True
    End If
'End If
End Sub

Public Sub UserForm_Activate()
HWNDActiveWindow
Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
m3 = 0
m4 = 0
bNewStep = False

' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
If MyClass.m2 = 1 Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
    ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    TogButFormat.Enabled = False
    TogButFormat.Value = False
    ColEl.Enabled = False
    Otv.Enabled = False
    RezOvt.Enabled = False
    Fask.Enabled = False
    Rad.Enabled = False
    OptPaz.Enabled = False
    Massiv.Enabled = False
    OptPlace.Enabled = False
    OptDim.Enabled = False
    OptExt.Enabled = False
    ChkDouble.Enabled = False
    ChkStar.Enabled = False
    CboStar.Enabled = False
    ChkDis.Enabled = False
    ChkHor.Enabled = False
    ChkChamfer.Enabled = False
    Faska.Enabled = False
    ChkDop.Enabled = False
    CboDop.Enabled = False
    ChkStep.Enabled = False
    CboStep.Enabled = False
    ChkLeft.Enabled = False
    CommandButton1.Enabled = False
    CmdClose.Enabled = False
    TxtUser.Visible = False
    TxtPref.Visible = False
    TxtSuf.Visible = False
    Exit Sub
Else ' |fffd||fffd||fffd| |fffd||fffd|
    Debug.Print "m5=", m5
    Set DimProp = MyClass.SelMgr.GetSelectedObject5(1) ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    If m5 = 1 Then ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        CommandButton1_Click
        m3 = 1
        Exit Sub
    Else ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        TogButFormat.Enabled = True
        ColEl.Enabled = True
        Otv.Enabled = True
        RezOvt.Enabled = True
        Fask.Enabled = True
        Rad.Enabled = True
        OptPaz.Enabled = True
        Massiv.Enabled = True
        OptPlace.Enabled = True
        OptDim.Enabled = True
        OptExt.Enabled = True
        ChkDouble.Enabled = True
        ChkStar.Enabled = True
        CboStar.Enabled = True
        ChkDis.Enabled = True
        ChkHor.Enabled = True
        ChkChamfer.Enabled = True
        Faska.Enabled = True
        ChkDop.Enabled = True
        CboDop.Enabled = True
        ChkStep.Enabled = True
        CboStep.Enabled = True
        ChkLeft.Enabled = True
        CommandButton1.Enabled = True
        CmdClose.Enabled = True
        TxtUser.Visible = True
        TxtPref.Visible = True
        TxtSuf.Visible = True
    End If
End If
Prefix = DimProp.GetText(swDimensionTextPrefix) ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Suffix = DimProp.GetText(swDimensionTextSuffix) ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
CalloutBelow = DimProp.GetText(swDimensionTextCalloutBelow) ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Set DP = DimProp.GetDimension() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
DPValue = DP.GetValue2("") ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
DimPrec = DimProp.GetPrimaryPrecision2 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
DPValuePr = DPValue
MyRound DPValuePr, DimPrec ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|

Set DispData = DimProp.GetDisplayData()
DisplayDataText = ""
For i = 0 To DispData.GetTextCount() - 1
    Debug.Print "DispData(" & i & ")=" & DispData.GetTextAtIndex(i)
    DisplayDataText = DisplayDataText & DispData.GetTextAtIndex(i)
Next i
sNewDim = Replace(DisplayDataText, Prefix, "", , 1)
sNewDim = Replace(sNewDim, Suffix, "", , 1)
sNewDim = Replace(sNewDim, Replace(CalloutBelow, "<stack>", ""), "")
sNewDim = Replace(sNewDim, Replace(CalloutBelow, "<stack size=0.2> <stack size=5>", ""), "")
sNewDim = Replace(sNewDim, Replace(CalloutBelow, "<stack size=0.25 divider=no> <stack size=4 divider=no>", ""), "")

If CStr(DPValuePr) = Trim(sNewDim) Then
    bNewDim = False
Else
    bNewDim = True
End If

Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd|=" & DPValuePr
Debug.Print "Prefix=" & DimProp.GetText(swDimensionTextPrefix)
Debug.Print "Suffix=" & DimProp.GetText(swDimensionTextSuffix)
Debug.Print "CalloutAbove=" & DimProp.GetText(swDimensionTextCalloutAbove)
Debug.Print "CalloutBelow=" & DimProp.GetText(swDimensionTextCalloutBelow)
Debug.Print "TextAll=" & DimProp.GetText(swDimensionTextAll)
Debug.Print "DisplayDataText=" & DisplayDataText


'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
ColEl.Clear ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
For i = 1 To 50
    ColEl.AddItem i
Next i

'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
Faska.Clear ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
Faska.AddItem "0,3"
Faska.AddItem "0,5"
Faska.AddItem "1"
Faska.AddItem "1,6"
Faska.AddItem "2"
Faska.ListIndex = 2

'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
CboDop.Clear ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
CboDop.AddItem "6g"
CboDop.AddItem "8g"
CboDop.AddItem "6H"
CboDop.AddItem "7H"
CboDop.ListIndex = 2

'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
CboStep.Clear ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
CboStep.AddItem "0,25"
CboStep.AddItem "0,35"
CboStep.AddItem "0,5"
CboStep.AddItem "0,75"
CboStep.AddItem "1"
CboStep.AddItem "1,5"
CboStep.AddItem "2"
CboStep.ListIndex = 2

'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
CboStar.Clear ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
CboStar.AddItem "*"
CboStar.AddItem "**"
CboStar.AddItem "***"
CboStar.ListIndex = 0

StartStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
StartStr2 = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
EndStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
BottomStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|

' ********* |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| **********
' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Prefix = Replace(Prefix, "|fffd|", "M")
Suffix = Replace(Suffix, "|fffd|", "x")
Suffix = Replace(Suffix, "-", "-")

' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Prefix = Replace(Prefix, "<MOD-PM>", Chr$(177))
Prefix = Replace(Prefix, "<MOD-DEG>", Chr$(176))
Prefix = Replace(Prefix, "<MOD-DIAM>", ChrW$(&HD8))
Prefix = Replace(Prefix, "<MOD-BOX>", ChrW$(&H25A1))

Suffix = Replace(Suffix, "<MOD-PM>", Chr$(177))
Suffix = Replace(Suffix, "<MOD-DEG>", Chr$(176))
Suffix = Replace(Suffix, "<MOD-DIAM>", ChrW$(&HD8))
Suffix = Replace(Suffix, "<MOD-BOX>", ChrW$(&H25A1))

CalloutBelow = Replace(CalloutBelow, "<MOD-PM>", Chr$(177))
CalloutBelow = Replace(CalloutBelow, "<MOD-DEG>", Chr$(176))
CalloutBelow = Replace(CalloutBelow, "<MOD-DIAM>", ChrW$(&HD8))
CalloutBelow = Replace(CalloutBelow, "<MOD-BOX>", ChrW$(&H25A1))

' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
varTemp = InStr(CalloutBelow, "stack size")
'Debug.Print "varTemp=", varTemp
If varTemp > 0 Then ' |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    ChkDouble.Value = True
    varTemp1 = InStr(CalloutBelow, "FONT size")
    If varTemp1 > 0 Then
        AStr = Right(CalloutBelow, Len(CalloutBelow) - 43)
    Else
        varTemp2 = InStr(CalloutBelow, "stack size=0.")
        If varTemp2 > 0 Then
            varTemp3 = InStr(CalloutBelow, "divider=no")
            If varTemp3 > 0 Then
                AStr = Right(CalloutBelow, Len(CalloutBelow) - 54)
            Else
                AStr = Right(CalloutBelow, Len(CalloutBelow) - 31)
            End If
        Else
            AStr = Right(CalloutBelow, Len(CalloutBelow) - 14)
        End If
    End If
    'Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
Else ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    ChkDouble.Value = False
    AStr = Prefix
    Debug.Print "|fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
End If
ChkDouble_Click

If InStr(Prefix, "M") > 0 Or InStr(sNewDim, "M") > 0 Then  ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    RezOvt.Value = True
    If InStr(Suffix, "/") > 0 Then ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
        ChkChamfer.Value = True
        Faska.Value = Mid(Suffix, InStr(Suffix, "/") + 1, InStr(InStr(Suffix, "/"), Suffix, "x") - InStr(Suffix, "/") - 1)
    Else ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|"
        ChkChamfer.Value = False
    End If
    
    If InStr(Suffix, "LH") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
        ChkLeft.Value = True
        If InStr(InStr(Suffix, "LH"), Suffix, "-") > 0 Then
            sDop = Mid(Suffix, InStr(InStr(Suffix, "LH"), Suffix, "-") + 1, 2)
        Else
            sDop = ""
        End If
    Else ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|"
        ChkLeft.Value = False
        If InStr(Suffix, "-") > 0 Then
            sDop = Mid(Suffix, InStr(Suffix, "-") + 1, 2)
        Else
            sDop = ""
        End If
    End If
    
    If sDop = "" Then  ' |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
        ChkDop.Value = False
    Else ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
        CboDop.Value = sDop
        ChkDop.Value = True
    End If
    
    If InStr(Suffix, "x") = 1 Or InStr(sNewDim, "x") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|"
        ChkStep.Value = True
        Numb = ""
        If bNewDim = True Then
            If InStr(sNewDim, "x") > 0 Then
                Numb = Right(sNewDim, Len(sNewDim) - InStr(sNewDim, "x"))
                bNewStep = True
            End If
        Else
            i = 2
            While IsNumeric(Mid(Suffix, i, 1)) = True Or InStr((Mid(Suffix, i, 1)), ",") > 0 Or InStr((Mid(Suffix, i, 1)), ".") > 0
                Numb = Numb & Mid(Suffix, i, 1)
                i = i + 1
            Wend
        End If
        CboStep.Value = Numb
    Else ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd|"
        ChkStep.Value = False
    End If
    RezOvt_Click
ElseIf InStr(Prefix, "R") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd|"
    Rad.Value = True
    Rad_Click
ElseIf InStr(Suffix, Chr$(176)) > 0 And InStr(Suffix, "/") = 0 Then ' |fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd|"
    Fask.Value = True
    Fask_Click
ElseIf InStr(AStr, "|fffd||fffd||fffd|") > 0 Then ' |fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd|"
    OptPaz.Value = True
    OptPaz_Click
ElseIf InStr(AStr, "|fffd||fffd||fffd||fffd||fffd||fffd|") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd|"
    OptExt.Value = True
    OptExt_Click
ElseIf InStr(Prefix, "=") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd|"
    Massiv.Value = True
    Massiv_Click
ElseIf InStr(AStr, "|fffd||fffd||fffd||fffd|") > 0 Then ' |fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd|"
    OptPlace.Value = True
    OptPlace_Click
ElseIf InStr(Prefix, ChrW$(&HD8)) > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    Otv.Value = True
    If InStr(Suffix, "/") > 0 Then ' |fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
        ChkChamfer.Value = True
        Faska.Value = Mid(Suffix, InStr(Suffix, "/") + 1, InStr(Suffix, "x") - InStr(Suffix, "/") - 1)
    Else
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|"
        ChkChamfer.Value = False
    End If
    Otv_Click
Else  ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
    OptDim.Value = True
    OptDim_Click
End If

If OptDim.Value = True Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    ColEl.Value = 1
Else
    ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    i = 1
    Numb = ""
    While IsNumeric(Mid(AStr, i, 1)) = True
        Numb = Numb & Mid(AStr, i, 1)
        i = i + 1
    Wend
    If Numb = "" Then  ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd|
        ColEl.Value = 1
    Else ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        ColEl.Value = Numb
    End If
    Debug.Print "*******", Numb, AStr
    
    ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| *
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| *"
    If InStr(Suffix, "*") > 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| *
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| *"
        ChkStar.Value = True
        CboStar.Value = Right(Suffix, Len(Suffix) - InStr(Suffix, "*") + 1)
    Else
        'Debug.Print "* |fffd||fffd||fffd|"
        ChkStar.Value = False
    End If
End If
ColEl_Change
ChkStar_Click
 
 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
Offset = DimProp.OffsetText
BrokenLeaderRet = DimProp.GetBrokenLeader2()
If Offset = True Then ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
    ChkDis.Value = True
Else
    'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
    ChkDis.Value = False
    If BrokenLeaderRet = 2 Then ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
        ChkHor.Value = True
    Else
        'Debug.Print "|fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
        ChkHor.Value = False
    End If
End If
m3 = 1
Debug.Print "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
Change
KeepFormOnTop
End Sub

Private Sub Change()
Debug.Print "Change"
StartStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
StartStr2 = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
EndStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
BottomStr = "" ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
Col = ColEl.ListIndex ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|

If Otv.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If ChkDouble.Value = True Then
        StartStr2 = "<MOD-DIAM>"
        BottomStr = ColEl.Value & " |fffd||fffd||fffd|."
    Else
        If Col = 0 Then
            StartStr = "<MOD-DIAM>"
        Else
            StartStr = ColEl.Value + " |fffd||fffd||fffd|.<MOD-DIAM>"
        End If
    End If
    If ChkChamfer.Value = 0 Or ChkChamfer.Enabled = False Then
    Else
        EndStr = "/" + Faska.Text + "x45<MOD-DEG>"
    End If
End If

If RezOvt.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If ChkDouble.Value = True Then
        StartStr2 = "M"
        BottomStr = ColEl.Value & " |fffd||fffd||fffd|."
    Else
        If Col = 0 Then
            StartStr = "M"
        Else
            StartStr = ColEl.Value & " |fffd||fffd||fffd|.M"
        End If
    End If
    If ChkLeft.Value = True Then
        sLeft = "-LH"
    Else
        sLeft = ""
    End If
    If ChkStep.Value = True Then
        sStep = "x" & CboStep.Value
    Else
        sStep = ""
    End If

    If ChkDop.Value = True Then
        sDop = "-" & CboDop.Value
    Else
        sDop = ""
    End If
    
    If ChkChamfer.Value = 0 Or ChkChamfer.Enabled = False Then
        EndStr = sStep & sLeft & sDop
    Else
        EndStr = sStep & sLeft & sDop & "/" & Faska.Text & "x45<MOD-DEG>"
    End If
End If
  
If Rad.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If ChkDouble.Value = True Then
        StartStr2 = "R"
        If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
            If ColEl.Value = 1 Then
            Else
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd|"
                    Else
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                    End If
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                End If
            End If
        Else
            If Right(ColEl.Value, 1) = 1 Then
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd|"
            ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
            Else
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
            End If
        End If
    Else
        If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
            If ColEl.Value = 1 Then
                StartStr = "R"
            Else
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd| R"
                    Else
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd| R"
                    End If
                Else
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| R"
                End If
            End If
        Else
            If Right(ColEl.Value, 1) = 1 Then
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd| R"
            ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd| R"
            Else
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| R"
            End If
        End If
    End If
End If
  
If Fask.Value Then ' |fffd||fffd||fffd||fffd||fffd|
    If ChkDouble.Value = True Then
        If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
            If Right(ColEl.Value, 2) < 5 Then
                If Right(ColEl.Value, 1) = 1 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                End If
            Else
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
            End If
        Else
            If Right(ColEl.Value, 1) = 1 Then
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
            ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
            Else
                BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
            End If
        End If
    Else
        If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
            If ColEl.Value = 1 Then
            Else
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                    Else
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                    End If
                Else
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                End If
            End If
        Else
            If Right(ColEl.Value, 1) = 1 Then
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
            ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
            Else
                StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
            End If
        End If
    End If
    EndStr = "x45<MOD-DEG>"
End If

If OptPaz.Value Then ' |fffd||fffd||fffd||fffd|
    If ColEl.Value < 2 Then
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| 2 |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
        ColEl.Value = 2
    Else
        If ChkDouble.Value = True Then
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd|"
                    Else
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd|"
                    End If
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd|"
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd|"
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                End If
            End If
        Else
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If ColEl.Value = 1 Then
                Else
                    If Right(ColEl.Value, 2) < 5 Then
                        If Right(ColEl.Value, 1) = 1 Then
                            StartStr = ColEl.Value + " |fffd||fffd||fffd| "
                        Else
                            StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd| "
                        End If
                    Else
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                    End If
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd| "
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd| "
                Else
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                End If
            End If
        End If
    End If
End If

If OptExt.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If ColEl.Value < 2 Then
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| 2 |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
        ColEl.Value = 2
    Else
        If ChkDouble.Value = True Then
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd|"
                    Else
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                    End If
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd|"
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
                End If
            End If
        Else
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If ColEl.Value = 1 Then
                Else
                    If Right(ColEl.Value, 2) < 5 Then
                        If Right(ColEl.Value, 1) = 1 Then
                            StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd| "
                        Else
                            StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd| "
                        End If
                    Else
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| "
                    End If
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd| "
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd| "
                Else
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| "
                End If
            End If
        End If
    End If
End If

If Massiv.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd|
    If ColEl.Value < 3 Or ColEl.Value = "" Then
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| 3 |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
        ColEl.Value = 3
    Else
        StepValue = DPValue / CDbl(ColEl.Value)
        MyRound StepValue, DimPrec + 1
        StartStr = ColEl.Value + "x" + CStr(StepValue) + "="
        EndStr = ""
    End If
End If

If OptPlace.Value Then ' |fffd||fffd||fffd||fffd||fffd|
    If ColEl.Value < 2 Then
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| 2 |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|"
        ColEl.Value = 2
    Else
        If ChkDouble.Value = True Then
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If Right(ColEl.Value, 2) < 5 Then
                    If Right(ColEl.Value, 1) = 1 Then
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                    Else
                        BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                    End If
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd|"
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd||fffd|"
                Else
                    BottomStr = ColEl.Value & " |fffd||fffd||fffd||fffd|"
                End If
            End If
        Else
            If Right(ColEl.Value, 2) <= 20 And Right(ColEl.Value, 2) <> 0 Then
                If ColEl.Value = 1 Then
                Else
                    If Right(ColEl.Value, 2) < 5 Then
                        If Right(ColEl.Value, 1) = 1 Then
                            StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                        Else
                            StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                        End If
                    Else
                        StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd| "
                    End If
                End If
            Else
                If Right(ColEl.Value, 1) = 1 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                ElseIf Right(ColEl.Value, 1) > 1 And Right(ColEl.Value, 1) < 5 Then
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd||fffd| "
                Else
                    StartStr = ColEl.Value + " |fffd||fffd||fffd||fffd| "
                End If
            End If
        End If
    End If
End If

If OptDim.Value Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    StartStr = Prefix
    BottomStr = CalloutBelow
    EndStr = Suffix
End If

' ******* |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| *******
' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
If DimProp.GetType() = 3 Then
    sDeg = Chr$(176)
Else
    sDeg = ""
End If
If OptDim.Value = True Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    StartStrPr = StartStr
    ENDstrPr = EndStr
    LblFirst.Caption = CStr(DPValuePr) & sDeg
    LblFirst.AutoSize = True
    LblFirst.Left = 318 - LblFirst.Width / 2
    TxtPref.Value = StartStrPr
    TxtPref.Width = 150 - LblFirst.Width / 2 + 5
    TxtPref.Left = 168
    TxtSuf.Value = ENDstrPr
    TxtSuf.Width = TxtPref.Width + 5
    TxtSuf.Left = 318 + LblFirst.Width / 2 - 10
    If ChkDouble.Value = True Then ' |fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        If varTemp > 0 Then
            If varTemp1 > 0 Then
                BottomStrPr = Right(BottomStr, Len(BottomStr) - 43)
            Else
                If varTemp2 > 0 Then
                    If varTemp3 > 0 Then
                        BottomStrPr = Right(BottomStr, Len(BottomStr) - 54)
                    Else
                        BottomStrPr = Right(BottomStr, Len(BottomStr) - 31)
                    End If
                Else
                    BottomStrPr = Right(BottomStr, Len(BottomStr) - 14)
                End If
            End If
        Else
            BottomStrPr = BottomStr
        End If
        TxtUser.Value = BottomStrPr
    Else ' |fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        TxtUser.Value = ""
        LblSecond.Caption = ""
    End If
Else ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    If ChkStar.Value = True Then
        EndStr = EndStr & CboStar.Value
    End If
    ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    StartStrPr = Replace(StartStr, "<MOD-DIAM>", ChrW$(&HD8))
    StartStr2Pr = Replace(StartStr2, "<MOD-DIAM>", ChrW$(&HD8))
    ENDstrPr = Replace(EndStr, "<MOD-DEG>", Chr$(176))
    
    If ChkDouble.Value = True Then ' |fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        BottomStrPr = BottomStr
        LblFirst.Caption = StartStr2Pr & CStr(DPValuePr) & sDeg & ENDstrPr ' & Chr(13) & Chr(10) & BottomStrPr
        LblSecond.Caption = BottomStrPr
    Else ' |fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        LblFirst.Caption = StartStrPr & CStr(DPValuePr) & ENDstrPr
        LblSecond.Caption = ""
    End If
    LblFirst.AutoSize = False
    LblFirst.Width = 300
    LblFirst.Left = 168
End If

If bNewDim = True And RezOvt.Value Then
    If ChkDouble.Value = True Then
        StartStr2 = "<MOD-DIAM>"
    Else
        If Col = 0 Then
            StartStr = "<MOD-DIAM>"
        Else
            StartStr = ColEl.Value & " |fffd||fffd||fffd|.<MOD-DIAM>"
        End If
    End If
    If bNewStep = True Then
        sStep = ""
    End If
    If ChkChamfer.Value = 0 Or ChkChamfer.Enabled = False Then
        EndStr = sStep & sLeft & sDop
    Else
        EndStr = sStep & sLeft & sDop & "/" & Faska.Text & "x45<MOD-DEG>"
    End If
End If

   
End Sub

Private Sub CommandButton1_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Debug.Print "CommandButton1_Click"
If OptDim.Value = True Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    StartStr = TxtPref.Value
    EndStr = TxtSuf.Value
    BottomStr = TxtUser.Value
   
    ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd| |fffd||fffd||fffd||fffd|
    StartStr = Replace(StartStr, Chr$(177), "<MOD-PM>")
    StartStr = Replace(StartStr, Chr$(176), "<MOD-DEG>")
    StartStr = Replace(StartStr, ChrW$(&HD8), "<MOD-DIAM>")
    StartStr = Replace(StartStr, ChrW$(&H25A1), "<MOD-BOX>")
    
    EndStr = Replace(EndStr, Chr$(177), "<MOD-PM>")
    EndStr = Replace(EndStr, Chr$(176), "<MOD-DEG>")
    EndStr = Replace(EndStr, ChrW$(&HD8), "<MOD-DIAM>")
    EndStr = Replace(EndStr, ChrW$(&H25A1), "<MOD-BOX>")
    
    BottomStr = Replace(BottomStr, Chr$(177), "<MOD-PM>")
    BottomStr = Replace(BottomStr, Chr$(176), "<MOD-DEG>")
    BottomStr = Replace(BottomStr, ChrW$(&HD8), "<MOD-DIAM>")
    BottomStr = Replace(BottomStr, ChrW$(&H25A1), "<MOD-BOX>")

    'cop = DimProp.SetText(swDimensionTextSuffix, EndStr)
    DimProp.SetText swDimensionTextSuffix, EndStr
    If ChkDouble.Value = True Then
        'cop = DimProp.SetText(swDimensionTextPrefix, " " & StartStr)
        'cop = DimProp.SetText(swDimensionTextCalloutBelow, "<stack size=0.2> <stack size=5>" & BottomStr)
        DimProp.SetText swDimensionTextPrefix, " " & StartStr
        DimProp.SetText swDimensionTextCalloutBelow, "<stack size=0.25 divider=no> <stack size=4 divider=no>" & BottomStr
    Else
        'cop = DimProp.SetText(swDimensionTextPrefix, StartStr)
        'cop = DimProp.SetText(swDimensionTextCalloutBelow, "")
        DimProp.SetText swDimensionTextPrefix, StartStr
        DimProp.SetText swDimensionTextCalloutBelow, ""
    End If
Else ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    'cop = DimProp.SetText(swDimensionTextSuffix, EndStr)
    DimProp.SetText swDimensionTextSuffix, EndStr
    If ChkDouble.Value = True Then ' |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        'cop = DimProp.SetText(swDimensionTextPrefix, " " & StartStr2)
        'cop = DimProp.SetText(swDimensionTextCalloutBelow, "<stack size=0.2> <stack size=5>" & BottomStr)
        DimProp.SetText swDimensionTextPrefix, " " & StartStr2
        DimProp.SetText swDimensionTextCalloutBelow, "<stack size=0.25 divider=no> <stack size=4 divider=no>" & BottomStr
    Else ' |fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
        'cop = DimProp.SetText(swDimensionTextPrefix, StartStr)
        'cop = DimProp.SetText(swDimensionTextCalloutBelow, "")
        DimProp.SetText swDimensionTextPrefix, StartStr
        DimProp.SetText swDimensionTextCalloutBelow, ""
    End If
End If
If ChkDis.Value = True Then
    Offset = True
Else
    Offset = False
    If ChkHor.Value = True Then
        ok = DimProp.SetBrokenLeader2(False, swBrokenLeaderHorizontalText)
    Else
        ok = DimProp.SetBrokenLeader2(True, swBrokenLeaderHorizontalText)
    End If
End If
DimProp.OffsetText = Offset
'ok = MyClass.ModelDoc2.GraphicsRedraw2()
MyClass.ModelDoc2.GraphicsRedraw2
End Sub

Private Sub UserForm_Terminate()
Unload Me
End
End Sub

Private Sub CmdClose_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
CommandButton1_Click
Unload Me
End
End Sub

Private Sub CommandButton2_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Unload Me
End
End Sub

Private Sub CmdCancel_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd|
UserForm_Activate
End Sub

Private Sub Fask_Click() ' |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "Fask_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_fask = 0
Else
    m_fask = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_fask = 1 Then
    m3 = 1
    Change
End If
Debug.Print "Fask_Click end", m3
End Sub

Private Sub Otv_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "Otv_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_Otv = 0
Else
    m_Otv = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
ChkChamfer.Enabled = True
ChkChamfer_Click
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_Otv = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "Otv_Click end", m3
End Sub

Private Sub Rad_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "Rad_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_Rad = 0
Else
    m_Rad = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_Rad = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "Rad_Click end", m3
End Sub

Private Sub OptPaz_Click() ' |fffd||fffd||fffd||fffd|
'Debug.Print "OptPaz_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_OptPaz = 0
Else
    m_OptPaz = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
If ColEl.Value < 2 Then
    ColEl.Value = 2
End If
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_OptPaz = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "OptPaz_Click end", m3
End Sub

Private Sub OptExt_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "OptExt_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_OptExt = 0
Else
    m_OptExt = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
If ColEl.Value < 2 Then
    ColEl.Value = 2
End If
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_OptExt = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "OptExt_Click end", m3
End Sub


Private Sub RezOvt_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "RezOvt_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_RezOvt = 0
Else
    m_RezOvt = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
ChkChamfer.Enabled = True
ChkChamfer_Click
ChkDop.Enabled = True
ChkDop_Click
If bNewStep = True Then
    ChkStep.Enabled = False
    CboStep.Enabled = False
Else
    ChkStep.Enabled = True
    ChkStep_Click
End If
ChkLeft.Enabled = True
ChkLeft_Click
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_RezOvt = 1 Then
    m3 = 1
    Change
End If
If bNewDim = True Then
    Otv.Enabled = False
    RezOvt.Enabled = False
    Fask.Enabled = False
    Rad.Enabled = False
    OptPaz.Enabled = False
    Massiv.Enabled = False
    OptPlace.Enabled = False
    OptDim.Enabled = False
    OptExt.Enabled = False
Else

End If
'Debug.Print "RezOvt_Click end", m3
End Sub

Private Sub Massiv_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "Massiv_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_Massiv = 0
Else
    m_Massiv = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
If ColEl.Value < 3 Then
    ColEl.Value = 3
End If
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ColEl.Enabled = True
ColEl_Change
ChkDouble.Value = False
ChkDouble.Enabled = False
If m_Massiv = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "Massiv_Click end", m3
End Sub

Private Sub OptPlace_Click() ' |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "OptPlace_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_OptPlace = 0
Else
    m_OptPlace = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 485
TxtPref.Visible = False
TxtSuf.Visible = False
If ColEl.Value < 2 Then
    ColEl.Value = 2
End If
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = True
ChkStar_Click
ChkDouble.Enabled = True
ChkDouble_Click
ColEl.Enabled = True
ColEl_Change
If m_OptPlace = 1 Then
    m3 = 1
    Change
End If
'Debug.Print "OptPlace_Click end", m3
End Sub

Private Sub OptDim_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "OptDim_Click", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_OptDim = 0
Else
    m_OptDim = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
FrmRecordDimM.Width = 521
TxtPref.Visible = True
TxtSuf.Visible = True
ChkChamfer.Enabled = False
Faska.Enabled = False
ChkDop.Enabled = False
CboDop.Enabled = False
CboStep.Enabled = False
ChkStep.Enabled = False
ChkLeft.Enabled = False
ChkStar.Enabled = False
CboStar.Enabled = False
ColEl.ListIndex = 0
ColEl.Enabled = False
ChkDouble.Enabled = True
'Debug.Print "***"
If varTemp > 0 Then ' |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    ChkDouble.Value = True
    Debug.Print "|fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
Else ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
    ChkDouble.Value = False
    Debug.Print "|fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|"
End If
ChkDouble_Click
If m_OptDim = 1 Then
    m3 = 1
    Change
End If
End Sub

Private Sub ColEl_Change() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ColEl_Change", m3
If m3 = 0 Then ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
    m_ColEl = 0
Else
    m_ColEl = 1 ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
End If
m3 = 0
If OptDim.Value = True Then
    ChkDouble.Enabled = True
Else
    If ColEl.ListIndex = 0 Or Massiv.Value = True Then
        ChkDouble.Value = False
        ChkDouble.Enabled = False
    Else
        ChkDouble.Enabled = True
    End If
End If
ChkDouble_Click
If m_ColEl = 1 Then
    m3 = 1
    Change
End If
End Sub

Private Sub ChkDouble_Click() ' |fffd| |fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkDouble_Click", m3, ChkDouble.Value
If ChkDouble.Value = True And OptDim.Value = True Then
    TxtUser.Visible = True
    LblSecond.Visible = False
Else
    TxtUser.Visible = False
    LblSecond.Visible = True
End If
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkChamfer_Click() ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkChamfer_Click"
If ChkChamfer.Value = 0 Then
    Faska.Enabled = False
Else
    Faska.Enabled = True
End If
If m3 = 1 Then
    Change
End If
End Sub

Private Sub Faska_Change() ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "Faska_Change"
If m3 = 1 Then
    Change
End If
End Sub

Private Sub CboDop_Change() ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "CboDop_Change"
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkDop_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkDop_Click"
If ChkDop.Value = 0 Then
    CboDop.Enabled = False
Else
    CboDop.Enabled = True
End If
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkLeft_Click() ' |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkLeft_Click"
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkStep_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd|
'Debug.Print "ChkStep_Click"
If ChkStep.Value = 0 Then
    CboStep.Enabled = False
Else
    CboStep.Enabled = True
End If
If m3 = 1 Then
    Change
End If
End Sub

Private Sub CboStep_Change() ' |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd|
'Debug.Print "CboStep_Change"
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkDis_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkDis_Click"
If ChkDis.Value = True Then
    ChkHor.Value = False
End If
End Sub

Private Sub ChkHor_Click() ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
'Debug.Print "ChkHor_Click"
If ChkHor.Value = True Then
    ChkDis.Value = False
End If
End Sub

Private Sub CboStar_Change() ' |fffd||fffd||fffd||fffd||fffd||fffd| *
'Debug.Print "CboStar_Change"
If m3 = 1 Then
    Change
End If
End Sub

Private Sub ChkStar_Click() ' *
'Debug.Print "ChkStar_Click"
If ChkStar.Value = True Then
    CboStar.Enabled = True
Else
    CboStar.Enabled = False
End If
If m3 = 1 Then
    Change
End If
End Sub

Private Sub TxtPref_MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
m4 = 1
End Sub

Private Sub TxtSuf_MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
m4 = 2
End Sub

Private Sub TxtUser_MouseDown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
m4 = 3
End Sub

Private Sub CmdDeg_Click()
Dim str1 As String, str2 As String
    If m4 = 1 Then
        str1 = Left(TxtPref, TxtPref.SelStart)
        str2 = Right(TxtPref, Len(TxtPref) - TxtPref.SelStart)
        TxtPref = str1 & Chr$(176) & str2
        TxtPref.SetFocus
    ElseIf m4 = 2 Then
        str1 = Left(TxtSuf, TxtSuf.SelStart)
        str2 = Right(TxtSuf, Len(TxtSuf) - TxtSuf.SelStart)
        TxtSuf = str1 & Chr$(176) & str2
        TxtSuf.SetFocus
    ElseIf m4 = 3 Then
        str1 = Left(TxtUser, TxtUser.SelStart)
        str2 = Right(TxtUser, Len(TxtUser) - TxtUser.SelStart)
        TxtUser = str1 & Chr$(176) & str2
        TxtUser.SetFocus
    Else
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    End If
End Sub

Private Sub CmdDiam_Click()
Dim str1 As String, str2 As String
    If m4 = 1 Then
        str1 = Left(TxtPref, TxtPref.SelStart)
        str2 = Right(TxtPref, Len(TxtPref) - TxtPref.SelStart)
        TxtPref = str1 & ChrW$(&HD8) & str2
        TxtPref.SetFocus
    ElseIf m4 = 2 Then
        str1 = Left(TxtSuf, TxtSuf.SelStart)
        str2 = Right(TxtSuf, Len(TxtSuf) - TxtSuf.SelStart)
        TxtSuf = str1 & ChrW$(&HD8) & str2
        TxtSuf.SetFocus
    ElseIf m4 = 3 Then
        str1 = Left(TxtUser, TxtUser.SelStart)
        str2 = Right(TxtUser, Len(TxtUser) - TxtUser.SelStart)
        TxtUser = str1 & ChrW$(&HD8) & str2
        TxtUser.SetFocus
    Else
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    End If
End Sub

Private Sub CmdPM_Click()
Dim str1 As String, str2 As String
    If m4 = 1 Then
        str1 = Left(TxtPref, TxtPref.SelStart)
        str2 = Right(TxtPref, Len(TxtPref) - TxtPref.SelStart)
        TxtPref = str1 & Chr$(177) & str2
        TxtPref.SetFocus
    ElseIf m4 = 2 Then
        str1 = Left(TxtSuf, TxtSuf.SelStart)
        str2 = Right(TxtSuf, Len(TxtSuf) - TxtSuf.SelStart)
        TxtSuf = str1 & Chr$(177) & str2
        TxtSuf.SetFocus
    ElseIf m4 = 3 Then
        str1 = Left(TxtUser, TxtUser.SelStart)
        str2 = Right(TxtUser, Len(TxtUser) - TxtUser.SelStart)
        TxtUser = str1 & Chr$(177) & str2
        TxtUser.SetFocus
    Else
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    End If
End Sub

Private Sub CmdSq_Click()
Dim str1 As String, str2 As String
    If m4 = 1 Then
        str1 = Left(TxtPref, TxtPref.SelStart)
        str2 = Right(TxtPref, Len(TxtPref) - TxtPref.SelStart)
        TxtPref = str1 & ChrW$(&H25A1) & str2
        TxtPref.SetFocus
    ElseIf m4 = 2 Then
        str1 = Left(TxtSuf, TxtSuf.SelStart)
        str2 = Right(TxtSuf, Len(TxtSuf) - TxtSuf.SelStart)
        TxtSuf = str1 & ChrW$(&H25A1) & str2
        TxtSuf.SetFocus
    ElseIf m4 = 3 Then
        str1 = Left(TxtUser, TxtUser.SelStart)
        str2 = Right(TxtUser, Len(TxtUser) - TxtUser.SelStart)
        TxtUser = str1 & ChrW$(&H25A1) & str2
        TxtUser.SetFocus
    Else
        MyClass.swApp.SendMsgToUser "|fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd|"
    End If
End Sub

Private Sub CmdAbout_Click()
MyClass.swApp.SendMsgToUser ("Made by Leon, 2007" & Chr$(10) & "|fffd||fffd||fffd||fffd| |fffd| |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd| |fffd||fffd||fffd| - Rich")
End Sub

Private Sub MyRound(RoundValue As Double, PrecValue As Long) ' |fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd||fffd|
Dim PrecValueInt As Integer
Dim Delta As Double
Dim j As Integer

PrecValue = Abs(PrecValue)
PrecValueInt = CInt(PrecValue)
j = 1
For i = 1 To PrecValueInt
    RoundValue = RoundValue * 10
    j = j * 10
Next i
Delta = RoundValue - Int(RoundValue)
If Delta >= 0.5 Then
    RoundValue = Int(RoundValue)
    RoundValue = RoundValue + 1
Else
    RoundValue = Int(RoundValue)
End If
RoundValue = RoundValue / j
End Sub

Attribute VB_Name = "RecordDimM_run"
Option Explicit
Public MyClass As New ClassRecordDimM

#If VBA7 Then
Public hwndAW As LongPtr
Public Declare PtrSafe Function GetActiveWindow _
  Lib "user32.dll" () As LongPtr
#Else
Public hwndAW As Long
Public Declare Function GetActiveWindow _
  Lib "user32.dll" () As Long
#End If

Sub main()
MyClass.MonitorSolidWorks
End Sub


Attribute VB_Name = "RecordDimM_top"
#If VBA7 Then
Private Declare PtrSafe Function SetWindowPos Lib "user32.dll" _
    (ByVal hwnd As LongPtr, _
    ByVal hWndInsertAfter As LongPtr, _
    ByVal X As Long, _
    ByVal Y As Long, _
    ByVal cx As Long, _
    ByVal cy As Long, _
    ByVal wFlags As Long) As Long
#Else
Private Declare Function SetWindowPos Lib "user32.dll" _
    (ByVal hwnd As Long, _
    ByVal hWndInsertAfter As Long, _
    ByVal X As Long, _
    ByVal Y As Long, _
    ByVal cx As Long, _
    ByVal cy As Long, _
    ByVal wFlags As Long) As Long
#End If

Public Sub HWNDActiveWindow()
    hwndAW = GetActiveWindow
End Sub

Public Sub KeepFormOnTop()

Dim RetVal As Long
  

Const SWP_NOMOVE = 2
Const SWP_NOSIZE = 1
Const SWP_WNDFLAGS = SWP_NOMOVE Or SWP_NOSIZE
Const HWND_TOP = 0
Const HWND_TOPMOST = -1
Const HWND_NOTOPMOST = -2

hwnd = hwndAW

RetVal = SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_WNDFLAGS)

End Sub

Public Sub NotKeepFormOnTop()

Dim RetVal As Long
  
Const SWP_NOMOVE = 2
Const SWP_NOSIZE = 1
Const SWP_WNDFLAGS = SWP_NOMOVE Or SWP_NOSIZE
Const HWND_TOP = 0
Const HWND_TOPMOST = -1
Const HWND_NOTOPMOST = -2

hwnd = hwndAW

RetVal = SetWindowPos(hwnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_WNDFLAGS)

End Sub






Attribute VB_Name = "ThisLibrary"
Attribute VB_Base = "0{801A2004-A66C-11D3-A8BD-0000861EBBD6}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True

' InQuest injected base64 decoded content
' BjYh
' BjYh

INQUEST-PP=macro
