Attribute VB_Name = "Module1"
Global ht_txt(999) As Double
Global nom_txt(999) As String




Sub textedyn()

' affiche dans la liste les styles de texte existants

Index = 0
For Each lst_style In ThisDrawing.TextStyles
f_txtdyn.liste_style.AddItem lst_style.Name


If lst_style.Name = ThisDrawing.GetVariable("textstyle") Then
    position = Index
    f_txtdyn.zs_hauteur.Text = lst_style.Height

    If Val(lst_style.Height) > 0 Then
        f_txtdyn.zs_hauteur.Enabled = False
        Else
        f_txtdyn.zs_hauteur.Text = ThisDrawing.GetVariable("textsize")
    End If

End If

' enregistre dans un tableau la hauteur du texte
' et la police de caract|fffd|res

ht_txt(Index) = lst_style.Height
nom_txt(Index) = lst_style.FontFile

Index = Index + 1

Next

f_txtdyn.liste_style.ListIndex = position
f_txtdyn.zs_police.Text = nom_txt(position)

'initialise les zones de saisie et options
f_txtdyn.zs_angle.Text = 0
f_txtdyn.option_gauche.Value = 1

' ouvre la fen|fffd|tre F_TXTDYN

f_txtdyn.Show

End Sub
Attribute VB_Name = "ThisDrawing"
Attribute VB_Base = "0{FCE25E01-1282-11D0-89E7-00805FC2FBBA}"
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True
Attribute VB_Name = "f_txtdyn"
Attribute VB_Base = "0{CFC1FD6A-4757-11D3-BF50-0080C8D346A3}{CFC1FD60-4757-11D3-BF50-0080C8D346A3}"
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False

Private Sub bt_annuler_Click()
ThisDrawing.SetVariable "users1", "annuler"
End
End Sub

Private Sub bt_ok_Click()

ThisDrawing.SetVariable "users1", "annuler"


If Val(zs_hauteur.Text) <= 0 Then
MsgBox "Hauteur de texte incorrecte.", vbCritical
zs_hauteur.SetFocus
Exit Sub
End If

If zs_angle.Text = "" Then
MsgBox "Angle incorrect.", vbCritical
zs_angle.SetFocus
Exit Sub
End If

' on m|fffd|morise dans la variable USERS2 la justification
' du texte

If option_gauche.Value = True Then
ThisDrawing.SetVariable "users2", "G"
End If

If option_droite.Value = True Then
ThisDrawing.SetVariable "users2", "D"
End If

If option_centre.Value = True Then
ThisDrawing.SetVariable "users2", "C"
End If

If option_fixe.Value = True Then
ThisDrawing.SetVariable "users2", "F"
End If

If option_milieu.Value = True Then
ThisDrawing.SetVariable "users2", "M"
End If

If option_aligne.Value = True Then
ThisDrawing.SetVariable "users2", "A"
End If

' on met courant le style de texte
ThisDrawing.SetVariable "textstyle", liste_style.List(liste_style.ListIndex)

' on m|fffd|morise dans la variable syst|fffd|me USERS3
' la hauteur du texte.
' Si = 0 alors hauteur fix|fffd|e dans le style
' si > 0 alors hauteur d|fffd|finit par l'utilisateur

If zs_hauteur.Enabled = False Then
ThisDrawing.SetVariable "users3", "F"
Else
ThisDrawing.SetVariable "users3", zs_hauteur.Text
End If

' on m|fffd|morise dans la variable syst|fffd|me USERR5
' l'angle d'|fffd|criture

ThisDrawing.SetVariable "userr5", Val(zs_angle.Text)

ThisDrawing.SetVariable "users1", "ok"


End
End Sub


Private Sub bt_style_Click()
ThisDrawing.SetVariable "users1", "ok"
ThisDrawing.SetVariable "users2", "CREATION"
End
End Sub

Private Sub liste_style_Change()

ThisDrawing.SetVariable "textstyle", liste_style.List(liste_style.ListIndex)

zs_hauteur.Text = ht_txt(liste_style.ListIndex)
zs_police.Text = nom_txt(liste_style.ListIndex)

If Val(ht_txt(liste_style.ListIndex)) > 0 Then
zs_hauteur.Enabled = False
Else
zs_hauteur.Enabled = True
End If


End Sub



INQUEST-PP=macro
